#+title: 24 09 04
#+bibliography: ../../references/master.bib
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />


This b/log will deal with Moishe Postone's 1993 book, /[[https://en.wikipedia.org/wiki/Time,_Labor_and_Social_Domination][Time, Labor and Social Domination: A Reinterpretation of Marx's Critical Theory]]/.
I read this over these past few summer months, as while it is 'only' around 400 pages, its argument is fundamental if one wants to reckon with Marx's thinking.[fn:1]

Postone proposes, in brief, that alienation is an impersonal form of social domination generated by labor itself, and that labor itself in Marx's analysis refers to a concept historically specific to capitalism.
This puts him at odds with what he calls *Traditional Marxism* (TM), a name designating all approaches "that analyze capital from the standpoint of labor and characterize that society essentially in terms of class relations"[cite:@postoneTimeLaborSocial1996 p.7].
For TM, because capitalist society is seen as a situation in which the social domination of one class over another can be overcome through a conscious effort at dispelling that domination-- by collectivizing the means of ownership, say-- disalienation is a (relatively) simple matter of focusing better on the right societal improvements.

Postone sees TM as a misunderstanding of the fundamentally dialectic (read: conceptually impossible to disentangle from each other) relationship between the spheres of *production* and *distribution*, spheres on which volumes 1 and 3 of /Capital/ respectively focus.
Distribution, in other words, is not a sphere of action that can be untethered from the machinations of value's creation in the sphere of production.
More concretely, this means that a revolution in the mode of distribution does not necessarily entail a concomitant revolution in the mode of production.
TM misunderstands the dialectical nature of distribution and production, then, when it posits that a more socialistic means of distributing the value of capitalistic production-- value that is quantified and circulated as *money*-- can upend the persistent dynamic of dispossession inherent to the movement of value that Marx calls capital as a whole.
Socialism, Postone cautions, is a revolution in the means and mode of distribution without posing  fundamental challenge to the dialectically inseparable conditions of value's production.
In this sense it is a false revolution, as it in fact results in nothing but the reinscription of capital's dynamic in a changed and potentially more disastrous form, the emperor in new and maybe more conniving clothes.

The misapprehension of capital's dynamic, and thus the path to its overcoming, Postone suggests, can be understood as a *critique of capitalism from the standpoint of labor*.
This standpoint assumes "labor" as a transhistorical category in Marx's analysis, a fundamental and unimpeachable force that operates in history.
This understanding struggles to reconcile macro-changes in the distributional phenomena of capitalism (such as the post-war expansion of the welfare state, the abolishing of the gold standard in Bretton Woods in the 1970s, and the ongoing informationalization of commodities) with the unchanging micro-stability of surplus value's constitutional sleight of hand in production.
For TM, these phenomena indicate capital losing grip, a transformation into something else.
Whether that something is better or worse than traditional capitalism is the only 'Marxist' thing left to dispute.

Marx's analysis in /Capital/, however, does not present "labor" as such a trans-historical force.
Instead of critiquing capitalism from the standpoint of labor, Marx's analysis is instead, Postone argues, a *critique of labor in capitalism* - that is, a critique of the concept of labor as capitalist logic would have it, from the standpoint of capital.

What does this mean, exactly?
Marx does not assume the role of a critic who stands outside society, calling out terms and logic for being fundamentally false, presuming a logically superior position from which he can identify some consciousnesses (capitalists) as flawed, and some (proletarians, or workers) as ethically superior.





* Footnotes

[fn:1] It is second only, perhaps, to Michael Heinrich's /[[https://en.wikipedia.org/wiki/An_Introduction_to_the_Three_Volumes_of_Karl_Marx%27s_Capital][Introduction to the Three Volumes of Marx's Capital]]/ as necessary supplementary reading for me. Alfred Sohn-Rethel's book /[[https://archive.org/details/intellectualmanu00sohn][Intellectual and Manual Labor: A Critique of Epistemology]]/ may also yet become crucial, though I am yet to properly deal with it. Similarly, have just started Beverly Best's new book, /[[https://www.versobooks.com/products/3032-the-automatic-fetish][The Automatic Fetish: The Law of Value in Marx's Capital]]/, which could become essential with regard to understanding /Capital, Volume III/. Rebecca Carson's /[[https://www.historicalmaterialism.org/book-series/immanent-externalities-the-reproduction-of-life-in-capital/][Immanent Externalities: The Reproduction of Life in Capital]]/ (which I have written about [[file:24-01-27.org][on this blog]]) is another important companion for me.
