#+title: 24 04 04
#+options: author:nil date:nil timestamp:nil toc:nil
#+bibliography: ../../references/master.bib
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />

This site has suffered another dramatic pause in proceedings, on the order of a month again, due to a writing submission that has at last been shipped.
The subject was Marx's qualification of the movement of value in /Capital/ as an "automatic subject" [cite:@marxCapitalCritiquePolitical1992 p.255], which I set out to assess in conversation with the human-machine relation in Marx, as part of a broader project that estimates whether there is anything to ground the capital-computer relation in value-theoretical philosophy.
As seems to be becoming typical of my writing process, I did not get as far into the matter in the allotted 20-25 double-spaced pages (the suggested length of the submission) as I had intended when laying out the essay's structure: yet this is by no means a bad thing, as it means that I have a very concrete idea of how to extend the essay I have just submitted should it turn out to be interesting enough (to its critics) to warrant that further engagement.

I am undecided on whether I ought to put up drafts such as this one just described here.
On the one hand, I see no good reason - in the spirit of writing not as a commercial and proprietary undertaking, but as a privilege for which the structure of a PhD luxuriantly gives me the time - to get into the habit of sitting on writing.
I understand that this is something of a common practice in academia; as writing /is/ a commercial asset, perhaps the most essential asset that humanistic scholars have to bargain with on the job market.
It is deemed essential, in this world, to be smart about where and when one publishes.
This requisite culture of smarts materializes (in America, at least, though I think elsewhere as well) in a proprietary and protective culture of knowledge production, in which younger scholars have to learn the unspoken principles of when to share, and when to sit quiet on an idea, for fear that someone might 'steal' it.

I have always found the rationalization of this culture somewhat absurd.
Isn't academia supposed to counterweight the capitalist enclosure of knowledge production, and offer space and time in which one can think "freely"?
Of course, there are the material realities of the job market - wherein junior scholars are fed the notion that it will hinder their chances of finding a position if they do not have a certain number of publications in a certain quality of journal - but don't many of us go into academia for the very point of thinking aspirationally otherwise?
This is not to condemn the student who "plays the game" effectively; but it is to suggest that, if there is anything counter-capitalist and free-thinking about academia as an alternative to corporate knowledge production, it must be more than just playing the game.
Is academia's atmosphere of career advancement really so suffocating that we should see so few students or professors (in the humanities) contesting the ossified publication pathways and experimenting with self-publishing drafts or other mechanisms of disseminating work beyond journal-ist enterprise?

The precarity of the humanities in tertiary institutions is no doubt a contributing factor.
Threatened by their growingly apparent "uselessness" as training for the wider world, degrees and departments in the humanities are subject to budget cuts and general deprioritization by administrative tiers of the university; tiers that seem to operate more and more according to a logic that treats the university as a (joint-stock?) company rather than a haven for academic freedom.
With fewer and fewer positions, it appears more and more stupid to go out on a limb and challenge the lineaments of what it means to be a successful scholar, especially in the earlier stages of one's career.
Hang tight to the fraying ropes of what tenure-track lines remain, the general prescription seems to be.
One's PhD is not the right time to question or challenge the gymnasium structure.

From the privileged vantage point of having a career (as a software engineer) that I can fall back on, this medicament seems too much like giving in to the predicament and letting capital run its course.
I am under no misconception that publishing drafts or pre-prints, rather than keeping quiet and hoping to instead get writing in prestigious and peer-reviewed journals, should represent any kind of anti- or counter-capitalist action.
But don't we agree that the academic journal system is broken?
Whether it always was, or whether the Internet (in conjunction with the PDF, perhaps) fundamentally undermined it, it seems silly to insist that we shouldn't experiment with Substack, with self-publication via public websites, etc, both as established academics and as early-stage scholars.
Will making pre-prints available nose-dive my chances of publishing anything in journals?
Will I then have to explain to future prospective employers why my publication credentials don't match the prestige of other candidates?
Maybe.
But I didn't come to grad school /solely/ to submit to a quiescent world of barriers to entry and false consciousness.
One must keep one's idealism too, if there is any hope of freedom.

#+print_bibliography:
