#+title: Why we should give feedback to students 
#+options: author:nil date:nil timestamp:nil

Today's work doesn't fit on one of my three tracks, as it consisted of grading papers from a course for which I was a TA (Teaching Assistant) in the Fall semester, /MCM 0150: Introduction to Modern Culture and Media/.
I submitted final grades for these papers for the students in my section in late December, but I had (until today) neglected to return students their final papers, annotated with comments.
Though returning these papers is not something that the course's professors nor the University would strictly enforce, as from their perspective a final grade is all that needs to be formally booked, it feels churlish to not do so.
As best I can, I am trying to avoid the commonplace duplicity of suggestion in academic life, in which professors consciously or otherwise suggest that they are "always" happy and available to review work, but then rarely actually get back to students when they recieve it.
I recognize that this attitude is produced by the increasingly neoliberal labour politics of the academy, in which the boundary between work and life is supposed to exist only for those who are not intellectually or emotionally equipped to deal with their collateralising.
As an aspiring academic, in other words, one feels one /must/ be open to be intellectually or pedagogically available to all opportunities, especially those that are not obligatory and/or are unpaid.
To refuse these would be, to use a phrase from my duologic life as a software engineer, to signal oneself as a bad 'cultural fit' for the academy.

I am against comporting oneself to such suggestions for their own sake, or for the sake of 'staying with the trouble'.
But giving time to students is an undertaking that deserves a different category, not least because it can often entail a rejection of the strictures and norms of the academy's labour expectations, rather than succumbing to them.
My interest in properly attending to papers students send to me is really more a reflection of the experience that I have had as an undergraduate student, as a working person, and also as a graduate student of struggling to find friends or fellows who will /actually/ read and discuss academic work.
There is a lot of posturing regarding interest in reading groups, extensions of seminar, and so on; but very few who want to make good on the promise that they will read something together, or offer comments on a work in progress.

There is of course an element of comfortability and community at play here, and I am not suggesting that everyone ought to be comfortable reading everything with everyone, or that anyone in particular should be comfortable reading any particular text with me, of all people.
But it is somewhat surprising that in a graduate body of nearly 3000, at least a third of which are notionally committed to some form of close reading as an occupational hazard, it is not straightforward to find others who want to make time to work through texts.
As an undergraduate at Princeton, I felt much the same.
(I effectively failed to start an extracurricular book club within a group of people who had 'literary' inclinations.)
During a stint working in Silicon Valley, I somewhat hilariously proposed to read Lampedusa's novel /Il Gattopardo/ (in the English translation of course) with aspiring tech aesthetes in an entity titled 'Club Book'.
After the first session (7pm after work on a Monday), it was clear that most attendants' idea of a book club was substantiated much more by alcohol consumption than it was reading or discussion.
As a researcher working at a human rights research group in London, I semi-successfully initiated an after-work reading group called [[https://argnotes.club/][A.R.G]] which ran more than 20 sessions; but even here there were really only one or two other regularly committed attendees.

The aesthetic of humanities at universities like Brown tells us that reading, writing, and thinking critically is important; yet the apparatus of attention around those activities (especially when they are not directly legitimised by institutions with names, or professors with titles) is often quite alienating.
Perhaps this is a luxury unique to the Ivy Leagues, which are admittedly the only schools at which I have formally pursued courses of study.
Indeed, many of my best experiences within these institutions have been with professors or students who have spent significant time at public institutions, in the U.S. or elsewhere.

So I spent three or four hours today annotated papers the grades for which I have already submitted.
# The only other progress made was to submit [[file:conference.marx-and-philosophy2024.pdf][an abstract]] for an upcoming conference at the Marx and Philosophy Society in London ([[https://philevents.org/event/show/118089][call for papers here]]).
