#+title: Uneasy Listening: Notes on Hearing and Being Heard 
#+options: author:nil date:nil timestamp:nil toc:nil
#+bibliography: ../../references/master.bib
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />

Re: [[https://mackbooks.co.uk/products/uneasy-listening-notes-on-hearing-and-being-heard][Uneasy Listening: Notes on Hearing and Being Heard]]:


This book is a captivating and succinct introduction to what I find important and interesting about psychoanalysis, and maybe Lacanian psychoanalysis in particular.
Grose's generous explanations/ruminations of/on the psychoanalytic endeavor are jarring in contrast to Brewer Young's type-written, "laconic", and abstract sections.
In the final dialogue, I could 'feel Grose's self-consciousness regarding her too-assumed role as analyst in her words, in the fractured attempt of this collaborative masterpiece.

The figure of a technically 'correct', scientific listening seems the substance of the strange desire Gore expresses to write this book in its beginning (for it would be hard to deny that, however collaborative a book might be, we can't but conceptualise its authorial beginning somewhere singular: and it is appropriately - laconically - the woman who inevitably bears this burden.
But yeah - what a masterclass in the art of conversation.
I was peeved at the beginning upon reading in that Grose "wrote him [Brewer Young] a letter asking if he would like to work on a very small book" [cite:@groseUneasyListeningNotes2022 p.8], as I thought: "she surely only wrote him an email."
Having read the book now, and having learned how Brewer Young inexplicably (laconically) wrote his sections on a type-writer, I am willing to revise the force of my "surely".
It seems the kind of retroaction in which this pair of writers might indeed actually engage.

I was also initially annoyed by the flirtatious finish to his [Brewer Young's] short starting letter; "the Lacanian likes of you, Anouchka, I felt, even more than felt, that your toolbox contained things that are acute, raise, and gentle" [cite:@groseUneasyListeningNotes2022 p.9].
I bet she's pretty, this Anouchka, and young.
Did Robert say yes to the project through some projection of desire, wanting to be nice and agreeable ("collaborative"), but secretly harbored some purposive hope to linger on her mind?
This was a cruel and suspicious thought, I think now, even if it is or was partially true.

And then Anouchka's flirty response on October 17th!
"I'm not sure how cut out I am to be a vampire. Vampires don't seem particularly interested in reciprocity and consent. I've invited Robert..."[cite:@groseUneasyListeningNotes2022 p.41].
I surely can't be the only one who reads this as a thinly veiled reference to /Twilight/.
Which would mean that Anouchka is flirting with the idea that she might not be cut out to be Bella?!
Or maybe I am: and so the thorough embarrassment I feel in coming to this Jacobian-reading is really a suspicious madness; and I should find someone (or something) to treat it.
I won't be able to stop myself looking up these people later today (once I have Internet), and checking in on the current status of their relationship to each other.
Lovers?
Friends?
Something disastrously in between?
You don't close a collaborative book project with a walk in a graveyard unless something sexual is going on, surely.

On a more academic note, I was surprised and charmed to read in Grose's first letter "A Short History of Psychoanalytic Listening" an account of Weizenbaum's /ELIZA/ and the spectre of machine-automated therapy.
Locating the analyst's listening as somewhere between the "too-much" of giving into counter-transference/instinctively recoiling from it (Josef Breuer and Anna O) and the "too-little" of the non-existent interlocutor (/ELIZA/, and now mindfulness apps) seems a beautiful way to frame the precarious problem of subjectivity.

I learned some, too, about what it looks like to be a clinical Lacanian.
That you don't believe in bringing a patient around to some constitutional reality (which makes sense, knowing in what I do of the impasse of the Lacanian Real); that you work in some shared art of fantasy to manufacture this surreal place of free association.
That in practice most analysts flout Freud's suggested mandates regarding the analysand's appropriate level of education, "fair reliable character" [cite:@groseUneasyListeningNotes2022 p.66], not being in states of confusion, and not being too old.
(Although Grose doesn't explicitly repudiate this last one.
Maybe she does tend toward younger patients.)

I also agree with Katherine Angel's assessment on the back cover of the book that it is often funny, as it made me laugh on several occasions.
For example, the "Conscious and Unconscious Bias" section (Grose's, little surprise): "When public figures rush off to get their unconscious racism sorted we probably all know what it's like to smirk a little." [cite:@groseUneasyListeningNotes2022 p.24];
"This is why strangers sometimes run away from analysts at parties; they think you'll be some smart alec who can see immediately, and will tell them, that they want to fuck their mum or kill their sister." [cite:@groseUneasyListeningNotes2022 p.25]; or: "In a paper called "Analysing, Not Psychoanalysing": he [Bernard Apfelbaum] writes about how to interpret without being a jerk. In this sense it a very important paper" [cite:@groseUneasyListeningNotes2022 p.28].
Brewer Young is less funny, I would say.
Though I did find it funny how unfunny he is in contrast to Grose, which is not necessarily something I think he wouldn't recognise.

* Bibliography
#+print_bibliography:
