#+title: Terry Eagleton: /Why Marx Was Right/
#+options: author:nil date:nil timestamp:nil toc:nil
#+bibliography: ../../references/master.bib
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />

Over the holiday period (which I count as the entirety of January, as my wedding took place on the 11th January, and I have not seriously returned to work until very recently) I read [[https://en.wikipedia.org/wiki/Why_Marx_Was_Right][Why Marx was Right]] by Terry Eagleton.
The book was given to me by my father-- over in Italy from New Zealand for the aforementioned wedding-- as he had gone out and bought it after I had sent my dissertation prospectus to the family group chat, a document that makes clear that Marx's thought is a very major focus in my current work.

I hadn't heard of the book before, and was delighted to discover what I think is a very accessible introduction to many of the key aspects of Marx's thought that drew and draw me to it. 
Indeed, I wish that I had known about the book when putting together the syllabus for my class on Marx last semester ([[./24-12-27.org][discussed in the first section here]]), as it guides the reader towards the salient aspects of why Marx remains relevant without assuming that they have already laboured through /Capital/.
Now that I have laboured through it, it has become the gateway drug I propose when accosted with the by-now-seemingly-age-old question, dredged up equally often in non-academic and academic discussions; 'but why study Marx'?

Each chapter in Eagleton's delectable little book takes a misconception about Marx head on, explaining why it is unfounded.
The [[https://en.wikipedia.org/wiki/Why_Marx_Was_Right][wikipedia page]] does an excellent job of outlining the lines of argumentation in summative depth, so I'll just bullet them here:

1. Marx's critique has no bearing on 21st century society, as it deals with 19th century concerns such as factories and food riots.
2. Marxism in theory is for faux-left academics, as in practice it always becomes ``a monstrously oppressive state". 
3. Marx's notion of history was overly deterministic, positing a 'necessary' transition to socialism/communism that never came about.
4. Humans are inherently selfish, and so the dream of communism is hopelessly utopian and fundamentally unrealistic.
5. Marx's thought was too invested in economic reduction, and as such is fundamentally less rich as a tradition of thought than more contemporary, more pluralistic alternatives. 
6. Marx's 'materialism' drains humanity of everything spiritual, crudely envisioning the worlds as nothing but what there is, and as such always ends up in undesirable states of society when applied, as the history of the 20th century proves.
7. Marx's conception of class is limited to his time, and can't help us to understand the diffuse hierarchies of social standing in today's world.
8. Marxist revolution is inherently violent.
9. Marxist revolution can only end in a Foucauldian all-powerful state, and thus the theory is inseparably married to unfreedom at some fundamental level.
10. The political Left today is not well-explained or supported by Marx or Marxism, and thus we should prefer other theories. 

Needless to say, as the sanguinely simple title of Eagleton's book implies, all of these allegations are unfounded at best; and more likely they are just plain wrong.
It is, in fact, astonishing how relevant Marx's thought remains today, given how much political and historical distance there is between us and him.
Indeed, we live in wake of an executive order given by a popularly elected president of the U.S. [[https://rollcall.com/2025/01/27/trump-white-house-orders-freeze-on-federal-grants-loans/][to root out 'Marxist equity']]; and I will continue to argue that concieving clearly of what such equity would look like if it were to appear is some of the most important scholarly work one can do.
If philosophy and critical thinking are to remain a valued part of organized society, we should carve out space and time for them at universities, even as the capitalist assault on the enduring value of critical thought intensifies (t)here. 

Eagleton's book is not just an accessible introduction, however.
Its footnotes are concise yet sharp, pointed the more interested reader towards secondary literature and sections of Marx's ouevre that deserve closer attention.
The influence of Fourier on Marx's political philosophy of utopia, for example, is a connection that I intend to follow up on in the coming months, having as it may interesting ramifications in the course of my study on what mathematical contours exist in /Capital/ and Marx's other works.
Balibar's book /Philosophy of Marx/-- which I had bulleted on my [[file:./24-01-26.org][lists]], but have still not yet read-- is also mentioned for Balibar's characterization of Marx as an /antiphilosopher/; a nomination that accords with my continually reinforced conception of Marx as one of the great masters of [[https://en.wikipedia.org/wiki/Hermeneutics_of_suspicion][suspicion]].

There are also some comments in the book that help me to carve out space to concieve of Marx's system as a philosophy (or anti-philosophy, perhaps) of the subject.
(No doubt this is the terrain that Balibar will cover in that book, when I finally come around to reading it.)
In the chapter on why Marx is not a crude materialist (chapter 6), for example, Eagleton cleverly shows how it is really capitalist 'philosophy' that is culpable of painting everything simply 'as it is', leaving no space for an imagination otherwise.
(This being the source of Fred Jameson's / Mark Fisher's [[https://www.reddit.com/r/zizek/comments/w0u7ca/who_actually_said_its_easier_to_imagine_the_end/][quip]] that 'it is easier to imagine the end of the world than it is the end of capitalism')
The unfreedom of imagination otherwise in capitalism, Eagleton argues, is a feature and not a bug for that system's zombified reproduction:

#+begin_quote
The prejudice that thought is independent of reality is itself shaped by social reality. [cite:@eagletonWhyMarxWas2011 p.135]
#+end_quote

It is not too far to go from this claim to the insight that consumed the working life of Alfred Sohn-Rethel, for which I quote from my prospectus:

#+begin_quote
Though Sohn-Rethel is best known for coining the phrase 'real abstraction' (principally popularized by way of its mention in Adorno's /Negative Dialectics/ [cite:@adornoLecturesNegativeDialectics2014]), the radical claim on which his sole philosophical monograph, /Intellectual and Manual Labor/, rests is this: "Exchange abstraction is not thought, but it has the form of thought" [cite:@sohn-rethelIntellectualManualLabour1978 p.99].
The idea that there is a /formal/ relation between the transcendental subject ("thought") and the political economy, i.e. the structure of a set of social relations that cannot necessarily be simply reduced to the sum of conscious operations of its constituents, situates Marx in a mathematical-philosophical lineage with which he is not always directly associated.
#+end_quote

Marx's work, as Eagleton recognizes, is not just a sociological, historically-specific treatise on the unjust structure of nascent capitalism in the 19th century; though it is certainly that.
It is also ``a theory of how historical animals function" [cite:@eagletonWhyMarxWas2011 p.158], which is to say, a philosophy of the (human) subject, a serious reckoning with whether or not there is anything philosophical (trans-historical) that can be said about society, or whether we are doomed to never be justified in abstracting from a specific time and a specific place, wherein not only is the map not the territory, but the map is never anything useful or justified at all.

* Bibliography
#+print_bibliography:
